spring:
  application:
    name: event
  datasource:
    url: jdbc:postgresql://localhost:5433/event-project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration